version: "2.1"
services:
  ###########################
  # Set up Apache PHP-fpm
  # http://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php.html
  ###########################
  apache:
    image: webdevops/php-apache-dev:7.4
    environment:
      php.max_input_vars: 30000
      php.post_max_size: 100M
      php.upload_max_filesize: 100M
      WEB_PHP_SOCKET: localhost:9000
      WEB_DOCUMENT_ROOT: /var/www/html
      WEB_DOCUMENT_INDEX: index.php
      # specify error log, otherwise might cause error
      # https://github.com/webdevops/Dockerfile/issues/242
      LOG_STDOUT: /var/log/httpd/apache.log
      LOG_STDERR: /var/log/httpd/apache_error.log
    restart: "no"
    volumes:
      - ./website/htdocs:/var/www/html
      - ./website/config:/var/www/config
      - ./logs:/var/log/httpd
      - ./backup:/var/www/backup

  ##########################
  # Setup the Database (MySQL) container
  ##########################
  mysql:
    build: ./docker/mysql # with your own my.cnf
    restart: "no"
    volumes:
      - ./data/mysql/runtime/mysql:/var/lib/mysql
      #    - ./data/mysql/runtime/mysql-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      #    - ./data/mysql/runtime/mysql-dump:/tmp/mysql-dump
      - ./data/mysql:/var/www/mysql
      - ./backup:/var/www/backup
      - ./docker/mysql/mysql_dev.cnf:/etc/mysql/conf.d/mysql_dev.cnf

  ###########################
  # Set up PhpMyAdmin
  ###########################
  phpmyadmin:
    build: ./docker/phpmyadmin
    restart: "no"

  ##########################
  # Setup the  MQ (RabbitMQ) container
  ##########################
  rabbitmq:
    build: ./docker/rabbitmq
    restart: "no"
    
  ##########################
  # Setup the  mongodb (MongoDB) container
  ##########################
  mongo:
      image: mongo
      volumes:
        - "./data/mongodb/db:/data/db"
      restart: "no"